inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
  Exclude:
    - 'config/environments/*'
    - 'db/schema.rb'
